[package]
name = "ip"
version = "1.0.0"
authors = ["FLAMINGO <flamingodev@outlook.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
