[package]
name = "ip"
version = "0.0.1"
authors = ["FLAMINGO <flamingodev@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
